version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.2.0
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # puerto API REST y gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333

volumes:
  qdrant_storage:
